### ISSUE TITLE
User Experience breaks on iOS chrome 

### ISSUE THREAD

**Issue by praveenramanathan** [JasonLovesDoggo/foodle#5]
When entering/typing the letters the rows collapse and are unintelligible 
![3D80F50D-0CC6-42A2-B2B7-D9515A5941C3](https://user-images.githubusercontent.com/3584990/171449315-366a959c-17e5-4f9b-9016-8ab99382891d.png)

**Comment by JasonLovesDoggo** [comment]
This will be a problem for me to debug as I don't personally own an iPhone, this will probably take a while

**Comment by JasonLovesDoggo** [comment]
latest commit should have fixed it.
